package pojo;
// Generated Oct 14, 2022 2:08:15 AM by Hibernate Tools 4.3.1

import DAO.DAOAdmin;
import javax.faces.bean.ManagedBean;
import java.util.List;
import DAO.DAOAdmin;




/**
 * Adminlogin generated by hbm2java
 */
@ManagedBean
public class Adminlogin  implements java.io.Serializable {


     private Integer idAdmin;
     private String username;
     private String password;
     
    public String login_admin(){
        DAOAdmin uDao = new DAOAdmin();
        List <Adminlogin> us = uDao.getBy(username, password);
        try {
            if (us != null) {
                username = us.get(0).username;
                password = us.get(0).password;
                return "admindash";
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        return "index";
    }
     
    public Adminlogin() {
    }

    public Adminlogin(String username, String password) {
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdAdmin() {
        return this.idAdmin;
    }
    
    public void setIdAdmin(Integer idAdmin) {
        this.idAdmin = idAdmin;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


